### ISSUE TITLE
twitter sdk is very large

### ISSUE THREAD

**Issue by Caij** [twitterdev/FabricWithTwitter#6]
Methods count：28  
Dependencies：11	   
JAR Size (KB)：21	    
DEX size (KB)：5
Dependencies methods count：      16851	   
Dependencies JAR size (KB) ：3208	
Dependencies DEX size (KB)： 2085

I just use the sharing features。What better way to do it？

**Comment by andypiper** [comment]
Hi there, this sample app is designed to demonstrate how to use Twitter Kit in a mobile app. We do work hard to keep the kit sizes small in Fabric so that they are easy to integrate.

Your question is probably better suited to our [developer forums](https://twittercommunity.com). One possibility might be to use Twitter4J directly inside your Android app.
